### ISSUE TITLE
cppcheck and iwyu not installed

### ISSUE THREAD

**Issue by flagarde** [Takishima/cmake-pre-commit-hooks#41]
Very nice hooks, It save a lot of work and configuration.

It seems the hooks cppcheck and iwyu cannot be run in pre-commit.ci because the corresponding programs are missing.

I seems possible to install micromamba,conda https://pypi.org/project/ensureconda/ using pip and then use micromamba to download this programs.

I tried to work on this but my knowledge and pre-commit hooks and even python is quite limited :(

**Comment by Takishima** [comment]
I am not particularly a fan of installing a local conda environment and then installing `cppcheck` or `iwyu` within it... 

This might run into some issues if the users are already using conda (though I am not sure since I am not a conda user myself).

But if you manage to convince me that such issues (like PATH modifications, adding local conda environment etc.)` are ok, then I wouldn't mind helping you implement this.

**Comment by LecrisUT** [comment]
Note that some distros do not have `iwyu`, e.g. Fedora.

**Comment by Takishima** [comment]
In those cases, you can skip the hooks when running `pre-commit` by specifying the `SKIP` environment variable.

For example:

```
SKIP=include-what-you-use pre-commit run --all-files
```

**Comment by LecrisUT** [comment]
I was giving a situation where it would be helpful to bundle iwyu. Ideally though,  these should be handled in the upstream distros.

**Comment by LecrisUT** [comment]
As a workaround, the action could be run on ubuntu or debian (seems only those package iwyu according to [pkgs.org](https://pkgs.org/search/?q=iwyu)) and install it manually. But I agree with @flagarde, that would be a cleaner approach.
